name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        #command: composer
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    
  notify:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.your-email.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Build Failed
        to: tongsreng@itc.edu.kh,
        from: github-actions@yourdomain.com
        content_type: text/plain
        body: Build failed for commit ${{ github.sha }} by ${{ github.actor }}.
    # - name: Run test suite
    #   run: composer run-script test
